### PR TITLE
Add KBYO form explainers article

### PR DESCRIPTION
**Pull request by marteki**
This is the second of a trio of KBYO articles, and is scheduled to be published today. It discusses the work done on the digital tools that help to explain the new Loan Estimate and Closing Disclosure forms.

Preview: http://marteki.github.io/cfpb.github.io/articles/helping-homebuyers-understand-new-mortgage-forms/

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Can you add semantic line breaks to make any editing easier? This looks fantastic and :+1: to merge!

**Comment by marteki** [comment]
Sorry about that! I always forget, and need to figure out how to make my code editors automagically do it for me.

(Side note: today I learned that you can't add hard wraps to the Jekyll front matter without bad things happening to the site.)

**Comment by KimberlyMunoz** [comment]
No problem, I forget too. :sparkler: Merging!

**Comment by marcesher** [comment]
hey @marteki I know this is late but hoping we can fix it: I noticed that the large image is > 1MB and took over 3 seconds to load. Perhaps this is an oversight? I imagine we'd want a much smaller-sized image here.

**Comment by marteki** [comment]
Total oversight. I just yanked the images without checking the size. :sob: 

I'll modify them quickly and send another PR through.

**Comment by marcesher** [comment]
Thanks, @marteki

**Pull request merged**
