### PR TITLE
Move Privacy Act statement to separate page

### PR DESCRIPTION
**Pull request by Scotchester**
Also updates `Gemfile.lock` for the latest version of the GitHub Pages gem.

## Testing
1. Pull branch
2. `bundle install`
3. `bundle exec jekyll serve --baseurl ''`
4. Go to <http://localhost:4000/>
5. Click the "View Privacy Act statement" link near the bottom of the homepage to see the new page.

## Please review
- @cfarm 
- @marteki 
- @jimmynotjim

### CODE REVIEW

**Comment by higs4281** [comment]
@Scotchester the line and new page works for me if I bump the version in Gemfile.lock back to nokogiri (1.6.7)

**Comment by higs4281** [comment]
👍 works on mac with a config param:
```
bundle config build.nokogiri --use-system-libraries
bundle install
```

**Comment by jimmynotjim** [comment]
Same as @higs4281. Mind updating the Readme for the time being with this instruction?

**Comment by Scotchester** [comment]
Note added to README! Mergin'.

**Pull request merged**
