### PR TITLE
Add post welcoming the 2015 T&I Fellows

### PR DESCRIPTION
**Pull request by Scotchester**
Also fixes a few warnings that arose when running `jekyll serve`.

### CODE REVIEW

**Comment by stephanieosan** [comment]
I don't have merge permissions, but this looks good!

**Comment by stephanieosan** [comment]
Thanks for the permissions, @dgreisen-cfpb !

**Comment by samhsimpson** [comment]
Yes, thanks @dgreisen-cfpb. 

I'll merge after @Scotchester updates Ashwin's bio.

**Pull request merged**
