### PR TITLE
fix asset paths and permalinks for articles

### PR DESCRIPTION
**Pull request by cfarm**
we think.

### CODE REVIEW

**Comment by willbarton** [comment]
tumblr_ntt9f8djjh1uuyy36o1_400

**Comment by Scotchester** [comment]
The removal of `assetpath` causes the site to break for anyone trying to preview it on their fork, e.g., http://cfarm.github.io/cfpb.github.io/

**Comment by ascott1** [comment]
@Scotchestercan you file an issue? The primary objective was getting the site back up and running and `assetpath` was not working.

**Comment by Scotchester** [comment]
Their permalink changes borked the `assetpath`, too? Weird. Okay, I'll file
a new issue.

**Comment by ascott1** [comment]
It could be as simple as not including or including a `/`

**Pull request merged**
