### PR TITLE
Add Iconathon article and images

### PR DESCRIPTION
**Pull request by willbarton**
This PR adds @ohsk's Iconathon article and its related images.

Preview: http://willbarton.github.io/cfpb.github.io/articles/collaborating-on-civic-symbols/

I'd like some suggestions on handling the images. This is the most image-heavy article we have, and prior articles haven't tried to do any particular image layout. I've tried to maintain the suggested layout, using inline styles. This raises a few questions:

1. Are inline styles OK here?
2. On smaller screens the images simply shrink in their current layout. This makes the side-by-side images a bit less than half of the screen width, which could be a bit small on something like an iPhone 4. Are we ok with this, or should that be handled differently?

Otherwise I think we're ready to publish!

### CODE REVIEW

**Comment by ielerol** [comment]
Ideally I'd like to see the images behave a little more responsively and stack at smaller sizes, but since they're not showing details of an interface they're not essential to understanding the article. For the purposes of getting this published in a timely manner, I'd say go ahead with what you have.

**Comment by willbarton** [comment]
Yup. I think it's something to flag as a concern going forward: how do we handle any custom CSS for articles.

**Comment by KimberlyMunoz** [comment]
I want to say there's something in Capital Framework that we can put the images in to have them have the right size and stack on mobile, but I have a bunch of tabs I need to finish responding to before I dive in.

**Comment by KimberlyMunoz** [comment]
Bleh. So I gave this a shot with `content-l_col content-l_col-1-2`, but we're actually not importing CF anywhere in this project. 

I'd go with inline styles for now and add a TODO to fix when we import cf-layout rather than creating a bunch of custom styles for each blog post, but that's just me.

**Comment by KimberlyMunoz** [comment]
Cool. I just added an issue so we remember to remove the inline styles later. :+1:

**Pull request merged**
