### PR TITLE
Summer Internship listing

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
I know it's an absurdly short job listing, but I got the summer internship listing up.

## Review
- @cfarm 
- @ascott1

### CODE REVIEW

**Comment by cfarm** [comment]
:+1: :+1: :+1: 

@Scotchester please to merge

**Comment by marteki** [comment]
Ashwin mentioned yesterday that if folks specifically mention T&I in their application, they get piped through to us easier.

Should we add a mention about that to the page in the hiring instructions section, or is it not that important?

**Comment by KimberlyMunoz** [comment]
I took the text straight from the PDF to avoid any problems with clearance. I'm not sure what the leeway is there, but we should probably handle it in another PR since it's likely to close before Friday.

**Comment by Scotchester** [comment]
Good point about clearance.

**Comment by KimberlyMunoz** [comment]
browserpreview_tmp-1

**Comment by cfarm** [comment]
@KimberlyMunoz nailed it

**Pull request merged**
