### PR TITLE
add links to graphic designer + CIO positions under "Work with us" section

### PR DESCRIPTION
**Pull request by cfarm**
We have a "Work with us" button + section on the homepage, so let's use it to point to the job posts.

## Changes

- Moved email sign up paragraph to make room for the positions link list
- updated CSS to make the paragraph text top aligned in the Work with us section

screen shot 2016-06-17 at 1 43 35 pm

screen shot 2016-06-17 at 1 42 39 pm

### CODE REVIEW

**Comment by stephanieosan** [comment]
:+1: Yes to this.

**Comment by Scotchester** [comment]
The CIO job posting is closed.

**Comment by cfarm** [comment]
whoops! updated to remove that list item.

**Comment by ascott1** [comment]
👍

**Pull request merged**
