### PR TITLE
Reduce sizes of images in form explainer articles 

### PR DESCRIPTION
**Pull request by marteki**
Mea culpa. :disappointed:

### CODE REVIEW

**Comment by Scotchester** [comment]
These are photographic and should probably be in JPEG format for the best quality/size balance. Did you try JPEG and see how they compared?

**Comment by marteki** [comment]
No, I didn't try JPEG. For some reason, I had in my head that we always defaulted to PNG.

More changes incoming.

**Comment by ascott1** [comment]
LGTM :+1:

**Comment by marcesher** [comment]
@marteki thanks!

**Pull request merged**
