### PR TITLE
Email

### PR DESCRIPTION
**Pull request by higs4281**
Reword email note and skillset line and fix capture of fullname

## Additions

- add class for full-name input so site.js can capture it for the email body
- exposes our email address so it can be copied by those not set up for mailto

## Changes

- Reword email note regarding resume
- Reword skillset line

## Deletions
- Awkward part of email note asking the user to delete the line. We can't ignore or delete the line on our end?

- @scotchester @jimmynotjim

## Screenshots
- What the sender sees  

what_sender_sees

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Nice :+1: Should have had the journalist involved from the beginning :laughing:

**Comment by Scotchester** [comment]
This isn't part of your current change set, but could you update the name of the input on L257 to be correct? Thanks!

**Comment by higs4281** [comment]
@Scotchester input name fixed

**Comment by Scotchester** [comment]
Thank you very much, @higs4281! :+1:

**Pull request merged**
