### PR TITLE
Mortgage toolkit article

### PR DESCRIPTION
**Pull request by ielerol**
Here's the mortgage toolkit article, the last of the three KBYO articles. You can preview the page here: http://ielerol.github.io/cfpb.github.io/articles/your-home-loan-toolkit/

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
LGTM, Can you add semantic line breaks to make any future edits/PRs easier to review?

https://github.com/cfpb/front-end/blob/master/markup.md#semantic-line-breaks-in-source-code

**Comment by mebates** [comment]
@ielerol - the crops on the first two images are incorrect. They should look more like what's in the google doc (much more zoomed in). Do you need me to make new files for you?

**Comment by ielerol** [comment]
@mebates sorry, I took those images from the google drive folder without checking them. I have the cropped version as well since I eventually figured out how to get them directly from the google document, I'll swap those out.

**Comment by ielerol** [comment]
@KimberlyMunoz thanks! I added semantic line breaks, and updated the images to the correct versions.

**Comment by mebates** [comment]
@ielerol can we make sure that they're the color corrected shots? i'll chat you the correct link

**Comment by ielerol** [comment]
ok, this time featuring correctly cropped AND color-corrected images, @mebates has confirmed.

**Comment by KimberlyMunoz** [comment]
:+1:

**Pull request merged**
